include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # General
    avoid_print: true
    constant_identifier_names: true
    one_member_abstracts: true
    super_goes_last: true
    type_init_formals: true

    # Flutter specific
    avoid_redundant_argument_values: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    sort_pub_dependencies: true
    use_build_context_synchronously: false

    # Dart specific
    avoid_relative_lib_imports: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true


analyzer:
  errors:
    invalid_annotation_target: error
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
